"""Add historial array to Tablero

Revision ID: 15bbaa3ab345
Revises: d7fe9b28528d
Create Date: 2026-02-22 01:38:43.950830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bbaa3ab345'
down_revision = 'd7fe9b28528d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tableros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historial', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tableros', schema=None) as batch_op:
        batch_op.drop_column('historial')

    # ### end Alembic commands ###
