"""Added is_admin to Usuario

Revision ID: d7fe9b28528d
Revises: 
Create Date: 2026-02-21 00:05:09.361555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7fe9b28528d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('nombre_completo', sa.String(length=120), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('suscripcion_activa', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tableros',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('icono', sa.String(length=10), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('creador_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('tablero_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tablero_id'], ['tableros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarjetas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('ocupacion', sa.String(length=100), nullable=True),
    sa.Column('nombre_conyuge', sa.String(length=100), nullable=True),
    sa.Column('numero_hijos', sa.Integer(), nullable=True),
    sa.Column('edades_hijos', sa.String(length=100), nullable=True),
    sa.Column('edad_conyuge', sa.Integer(), nullable=True),
    sa.Column('telefono_conyuge', sa.String(length=50), nullable=True),
    sa.Column('email_conyuge', sa.String(length=120), nullable=True),
    sa.Column('trabajo_conyuge', sa.String(length=100), nullable=True),
    sa.Column('fecha_matrimonio', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('bautizado', sa.Boolean(), nullable=True),
    sa.Column('es_lider', sa.Boolean(), nullable=True),
    sa.Column('ministerio', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('lista_id', sa.String(length=36), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarjetas')
    op.drop_table('listas')
    op.drop_table('tableros')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
